/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kashtkarzarai.dialog;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import kashtkarzarai.bean.CustomerBeans;
import kashtkarzarai.bean.UOMBeans;
import kashtkarzarai.dao.UomDao;
import kashtkarzarai.daoImpl.UomDaoImpl;

/**
 *
 * @author Vksoni
 */
public class SetingJDialog extends javax.swing.JDialog {

    DefaultTableModel tableModelUOM;
    public ArrayList<UOMBeans> uom_list;
    UomDao uom;

    /**
     * Creates new form SetingJDialog
     */
    public SetingJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        uom = new UomDaoImpl();
        tableModelUOM = (DefaultTableModel) this.jTableUOM.getModel();

        JTableHeader header = this.jTableUOM.getTableHeader();
        header.setBackground(new Color(0, 204, 0));
        header.setForeground(new Color(255, 255, 255));
        header.setFont(new Font("SansSerif", Font.BOLD, 18));
        showInTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAd = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldUOM = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUOM = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/plus-icon-0.png"))); // NOI18N
        jButtonAd.setBorder(null);
        jButtonAd.setBorderPainted(false);
        jButtonAd.setContentAreaFilled(false);
        jButtonAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 40, 40));

        jButtonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/Minus_icon.png"))); // NOI18N
        jButtonDel.setBorder(null);
        jButtonDel.setBorderPainted(false);
        jButtonDel.setContentAreaFilled(false);
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 40, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 180, -1));

        jTextFieldUOM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUOM.setBorder(null);
        jTextFieldUOM.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldUOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUOMMouseClicked(evt);
            }
        });
        jTextFieldUOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUOMActionPerformed(evt);
            }
        });
        jTextFieldUOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUOMKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldUOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 180, -1));

        jTableUOM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableUOM.setForeground(new java.awt.Color(0, 0, 51));
        jTableUOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUOM.setToolTipText("Products");
        jTableUOM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUOM.setGridColor(new java.awt.Color(0, 0, 51));
        jTableUOM.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableUOM.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableUOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUOMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableUOM);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 370));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("UOM*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdActionPerformed
        // TODO add your handling code here:
        if (!(this.jTextFieldUOM.getText().equals(""))) {
            uom.saveUom(new UOMBeans(0, this.jTextFieldUOM.getText().trim()));
            JOptionPane.showMessageDialog(this, this.jTextFieldUOM.getText() + " Added succesfully ", "Added", JOptionPane.DEFAULT_OPTION);
            this.jTextFieldUOM.setText("");
            showInTable();
            

        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field", "Added", JOptionPane.DEFAULT_OPTION);

        }
    }//GEN-LAST:event_jButtonAdActionPerformed

    private void jTextFieldUOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUOMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUOMMouseClicked

    private void jTextFieldUOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUOMActionPerformed

    private void jTextFieldUOMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUOMKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUOMKeyPressed

    private void jTableUOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUOMMouseClicked


    }//GEN-LAST:event_jTableUOMMouseClicked

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:

        if (!(this.jTableUOM.getSelectedRow() == -1)) {
            int uom_id = uom_list.get(this.jTableUOM.getSelectedRow()).getUom_id();
            uom.removeUom(new UOMBeans(uom_id, ""));
            showInTable();
        }
         else {
            JOptionPane.showMessageDialog(this, "Select UOM from table to delete ", "Error", JOptionPane.DEFAULT_OPTION);

        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SetingJDialog dialog = new SetingJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void showInTable() {
        tableModelUOM.setRowCount(0);

        uom_list = uom.getAllUom();
        for (UOMBeans uom : uom_list) {
            Vector V = new Vector();
            V.add(uom.getUom());

            tableModelUOM.addRow(V);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableUOM;
    private javax.swing.JTextField jTextFieldUOM;
    // End of variables declaration//GEN-END:variables
}
