/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kashtkarzarai.frames;

import java.awt.Toolkit;
import java.io.File;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kashtkarzarai.dialog.SetingJDialog;
import org.eclipse.birt.core.framework.Platform;
import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.HTMLRenderOption;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportEngineFactory;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.engine.api.IRunAndRenderTask;


/**
 *
 * @author Vksoni
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.jButtonReport.setVisible(true);
        this.jLabelloading.setVisible(false);
        icon();
        watch();
    }
    private void icon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/icon.jpg")));
        
    }
        int hour,min,sec,am_pm =0;
    String day,NowTime;
    int time =0;
    public void watch(){
    
    new Thread() {
            public void run() {
                while (time == 0) {
                    Calendar cal = new GregorianCalendar();
                     hour = cal.get(Calendar.HOUR);
                     min = cal.get(Calendar.MINUTE);
                     sec = cal.get(Calendar.SECOND);
                     am_pm = cal.get(Calendar.AM_PM);
                    
                    
                    if (am_pm == 1) {
                        day = "PM";
                    } else {
                        day = "AM";
                        
                    }
                    
                     NowTime = hour + ":" + min + ":" + sec + " " + day;
                    watch.setText(NowTime);
                    
                }
                
            }
            
        }.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCompany = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonProduct = new javax.swing.JButton();
        jButtonUsers = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonReport = new javax.swing.JButton();
        jLabelloading = new javax.swing.JLabel();
        jButtonCustomerRecords = new javax.swing.JButton();
        jButtonLogin11 = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        watch = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCompany.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCompany.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCompany.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/company_1.png"))); // NOI18N
        jButtonCompany.setText("Company");
        jButtonCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompanyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 310, 120));

        jLabel2.setBackground(new java.awt.Color(0, 204, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kashtkar Zarai Markaz");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jButtonProduct.setBackground(new java.awt.Color(0, 204, 0));
        jButtonProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/agructula products.png"))); // NOI18N
        jButtonProduct.setText("Products By Company");
        jButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 310, 120));

        jButtonUsers.setBackground(new java.awt.Color(0, 204, 0));
        jButtonUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUsers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/user login.png"))); // NOI18N
        jButtonUsers.setText("User Accounts");
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 310, 120));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/setings.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 60, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/logo1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 130));

        jButtonReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/report.png"))); // NOI18N
        jButtonReport.setBorder(null);
        jButtonReport.setBorderPainted(false);
        jButtonReport.setContentAreaFilled(false);
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 60, 70));

        jLabelloading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/loading.gif"))); // NOI18N
        jLabelloading.setText("jLabel4");
        jPanel1.add(jLabelloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 250, 100));

        jButtonCustomerRecords.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCustomerRecords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCustomerRecords.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCustomerRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/user.png"))); // NOI18N
        jButtonCustomerRecords.setText("Customer Records");
        jButtonCustomerRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCustomerRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 310, 120));

        jButtonLogin11.setBackground(new java.awt.Color(0, 204, 0));
        jButtonLogin11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLogin11.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/sale.png"))); // NOI18N
        jButtonLogin11.setText("Sale");
        jButtonLogin11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 120));

        jButtonCustomer.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/user-male-3.png"))); // NOI18N
        jButtonCustomer.setText("Customer");
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 310, 120));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Sinjhoro");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kashtkarzarai/images/homebackgroun.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 180));

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kashtkar Zarai Markaz");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        watch.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        watch.setForeground(new java.awt.Color(255, 255, 255));
        watch.setText("jLabel8");
        getContentPane().add(watch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Software Designed By: Zaptox");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 190, 30));

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All rights reserved @Kashtkarzarai|2018");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1010, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompanyActionPerformed
        new CompanyForm().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCompanyActionPerformed

    private void jButtonCustomerRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerRecordsActionPerformed
        // TODO add your handling code here:
        new CustomerRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomerRecordsActionPerformed

    private void jButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductActionPerformed
        // TODO add your handling code here:
        new CompanyProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProductActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        // TODO add your handling code here:
        new CustomerPage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaleActionPerformed
        // TODO add your handling code here:
        new SalePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSaleActionPerformed

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // TODO add your handling code here:
        new UserPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new SetingJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportActionPerformed
        this.jLabelloading.setVisible(true);

        this.jButtonReport.setVisible(false);
        genReport();
        this.jButtonReport.setVisible(true);
        this.jLabelloading.setVisible(false);

    }//GEN-LAST:event_jButtonReportActionPerformed

    private void jButtonReportItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButtonReportItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportItemStateChanged

    private void jButtonLogin11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin11ActionPerformed
        // TODO add your handling code here:
        new SalePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogin11ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    public void genReport() {

        new Thread(new Runnable() {

            int i = 1;

            @Override
            public void run() {
                while (true) {
                    i += 10;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }).start();

        IReportEngine engine = null;
        EngineConfig config = null;
        String report_name = "Report of Month ";
        try {

            config = new EngineConfig();
            //config.setLogConfig("c:/temp/test", Level.FINEST);
            Platform.startup(config);
            IReportEngineFactory factory = (IReportEngineFactory) Platform
                    .createFactoryObject(IReportEngineFactory.EXTENSION_REPORT_ENGINE_FACTORY);
            engine = factory.createReportEngine(config);

            IReportRunnable design = null;
            //Open the report design
            String rpath = "monthlySalesReport.rptdesign";

            design = engine.openReportDesign(rpath);

            IRunAndRenderTask task = engine.createRunAndRenderTask(design);
//           task.setParameterValue("custo_id", ""+6);
//            task.validateParameters();
//            // int order=DbManager.getMaxOrder();
            HTMLRenderOption options = new HTMLRenderOption();
            options.setOutputFileName("Reports\\MonthlyReports/" + report_name + ".pdf");
            options.setOutputFormat("pdf");

            //options.setHtmlRtLFlag(false);
            //options.setEmbeddable(false);
            //options.setImageDirectory("C:\\test\\images");
            //PDFRenderOption options = new PDFRenderOption();
            //options.setOutputFileName("c:/temp/test.pdf");
            //options.setOutputFormat("pdf");
            task.setRenderOption(options);
            task.run();
            task.close();
            engine.destroy();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } finally {
            Platform.shutdown();
            System.out.println("reportGenerated");
            JOptionPane.showMessageDialog(rootPane, "report scucessfully generated");

            try {

                if ((new File("Reports\\MonthlyReports/" + report_name + ".pdf")).exists()) {

                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler Reports\\MonthlyReports/" + report_name + ".pdf");
                    p.waitFor();

                } else {

                    System.out.println("File is not exists");

                }

                System.out.println("Done");

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCompany;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonCustomerRecords;
    private javax.swing.JButton jButtonLogin11;
    private javax.swing.JButton jButtonProduct;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelloading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel watch;
    // End of variables declaration//GEN-END:variables
}
